#ifndef CONFIG_HPP_INCLUDED
#define CONFIG_HPP_INCLUDED

#define BETA 0
#define INDEV 1
#define SNAPSHOT 2
#define RELEASE 3

#define STABLE 1
#define NIGHTLY 0

#define SILLYRABBIT_VERSION_STATUS BETA
#define SILLYRABBIT_STABLE_STATUS NIGHTLY

#define SILLYRABBIT_MAJOR_VERSION 1
#define SILLYRABBIT_MINOR_VERSION 2
#define SILLYRABBIT_PATCH_VERSION 0

#endif
